### ISSUE TITLE
要望：画面幅縮小対応

### ISSUE THREAD

**Issue by brexbrex13** [totono/todo3#10]
おそらく現在は想定していないと思うが、幅を狭くすると
　左側　詳細入力の"＞"ボタン、
　右側　登録の"＋"ボタン
が入力ボックスに重なる。
特に左側の＞はDatepickerにフォーカスが持っていかれるので押せなくなる。
![image](https://user-images.githubusercontent.com/119271566/228100360-1a6185b4-44b4-4311-b6fd-a886f0402845.png)

↑で440pxくらい（ペイントで確認）

**Comment by totono** [comment]
どれぐらい狭くできたらいい？

**Comment by totono** [comment]
#11 
もし詳細入力と通知しないチェックをタスク入力欄から消していいなら、> もいらなくなると思うけど、どうやろか

**Comment by brexbrex13** [comment]
触った感じだとDeletedタブの横にもう一つタブ分くらいの幅（400pxくらい？）のイメージかも。
詳細入力編集対応なら、たしかに＞は要らんな。なんなら＋ボタンもいらんかも（基本Enterで登録してる）
今風のイメージならテキストボックス右側に→ボタンがある感じ

**Comment by totono** [comment]
400pxぐらいでやってみるか。datepickerの年っていると思う？
内部的には年は持つけど表示上は月日だけで良いんじゃね？

**Comment by brexbrex13** [comment]
確かに表示上は月日でいいな

**Comment by totono** [comment]
・ヘッダーの編集機能の削除により展開アイコンを削除した
・またタスクの追加ボタンを削除した
・レイアウトの見直し
により幅の縮小しやすくしたので
