### ISSUE TITLE
要望：詳細入力ボタン位置変更または編集可

### ISSUE THREAD

**Issue by brexbrex13** [totono/todo3#11]
+ボタン＝詳細入力の拡張のイメージでクリックしちゃいます。
登録後入力（編集）出来るようにするレベルでも良いかも

**Comment by totono** [comment]
登録後の編集は、登録後のタスクを展開したらテキストエリアが表示されて、いつでも編集できるみたいなイメージでいい？
編集ボタンを押すと編集可能になるとかいる？
通知するしないのチェックもそこに移動でいい？

**Comment by brexbrex13** [comment]
・テキストエリアでも編集ボタンでも簡単な方で問題ないかな（ゴミ箱の横あたりにペンマークとか。）
　↑実装されたら、タスク登録時点の拡張登録はいらんかもしれん

・通知しないチェックも登録後チェックに移動でいいかな。
　今風にするならベルのアイコンを表示して、斜線か色変更で切換えとかだとわかりやすいかも

**Comment by totono** [comment]
じゃあ タスク登録時の > で展開する詳細入力は消す方向で。
ベルアイコンは考えとくわ
