### ISSUE TITLE
多重起動防止

### ISSUE THREAD

**Issue by brexbrex13** [totono/todo3#15]
タスクトレイに入れた状態でexeを叩くと多重起動できてしまう。

ちょっとイレギュラーな使い方かもしれないが、タスクバーにピン止めして使っており、
タスクトレイに格納状態でタスクバーのアイコンをクリックすると起動判定になるみたい。

**Comment by brexbrex13** [comment]
訂正：タスクトレイに入れてなくても多重起動できました

**Comment by totono** [comment]
多重起動防止はできると思うけど、
タスクバーにピン止めしてるなら、ピン止めしたアイコンクリックしても無反応になりそうな気がする。それでよい？

**Comment by totono** [comment]
あー、多重起動をしようとした時の制御はできるっぽいな。
タスクトレイに入ってるときにピン止めしたアイコンをクリックしたら、多重起動せずアプリを表示してフォーカスで良いのかな？

**Comment by brexbrex13** [comment]
＞タスクトレイに入ってるときにピン止めしたアイコンをクリックしたら、多重起動せずアプリを表示してフォーカス
これでお願いします
（トレイアイコンクリックで表示させたのと同じ動きになるイメージだった）
