### ISSUE TITLE
通知周り

### ISSUE THREAD

**Issue by brexbrex13** [totono/todo3#16]
1. 表示した状態で通知時間を向かえると当該タスクが赤文字にならない（白文字のまま）
　（特に問題はないが一応。タスク登録やタブ切り替えすると変わるので画面更新されるトリガがないためと思われる。）

2.既知要望と思うが赤文字だとやっぱ強調感ないので変更希望 
　（行のbgカラーを変更？）

3.将来機能でもよいが、リマインダーの再セットが出来ると助かる
　（時間なのはわかったけど今は無理なので再通知よろ！
　　というときに時間だけちょこっと変えて再登録する感じ）

**Comment by totono** [comment]
1
#18 
2
#19 
3
#17 
それぞれ起票
