### ISSUE TITLE
リマインダーの再セット

### ISSUE THREAD

**Issue by totono** [totono/todo3#17]
〇〇時間後に再通知、みたいなのが出来ればよい？
それともそもそも、登録したタスクの編集機能で時間を再設定できればよいのか？

**Comment by brexbrex13** [comment]
いろんなパターンがありそうだから再設定のほうが良さそう。
（1分後、5分後、10分後・・・とか色々用意しないといけなさそう。）

たとえば通知済タスクに「Remind」ボタンが出てきて押したら登録ボックスにそっくり内容が転記される
（つまり流用して新規登録）
くらいでもいいかなと思ったけど、確かに通知前のタスクの再設定もしたくなるときがありそうだし
編集機能として実装したほうがいいかも

**Comment by totono** [comment]
編集機能としたほうがいろいろ融通利きそうだからそうしよう

**Comment by totono** [comment]
#11 
編集機能を追加した
