### ISSUE TITLE
通知は時間でしか判定していないかも

### ISSUE THREAD

**Issue by brexbrex13** [totono/todo3#26]
4/19 10:00に設定したタスクが、今日（3/29）の10:00に通知された。
テストで未来の日付＋時間で試してみたけど、同じ動作なので、
時間部分でしか判定していないっぽい。

タスクの文字は赤字にならなかったので、通知動作の判定条件に問題がありそう

**Comment by totono** [comment]
年月日でも見てたと思うんだけどなぁ調べます
