### ISSUE TITLE
編集モードでチェックボタンを押すと完了扱いになる

### ISSUE THREAD

**Issue by brexbrex13** [totono/todo3#52]
チェックボタンを押したあと、判定が残っててCompleteが押されてしまっているのか？
チェックボタンの左端を押すと確かに編集になるが、
右側あたりを押すとComplete扱いになるっぽい。

**Comment by brexbrex13** [comment]
何回か試したら、押す場所じゃなくて、
チェックボタン押したときに通知時刻を超えていると勝手に完了扱いになるっぽい？

**Comment by totono** [comment]
編集した日時が現在日時より前だった場合は完了扱いにしてる。後だった場合は未完了になる

timepickerを開いて、どっか別のとこクリックしてpickerを閉じないと、値が確定されないようになってる

そんで、たぶんtimepickerを開いたままチェックボタン押してるから、編集前の13:00のままになってしまってるんだわ
これどうすっかなー

わかってると思うから念の為だけど、ここパブリックだから、機密になりうる写真とかはあげないようにね

**Comment by totono** [comment]
> timepickerを開いて、どっか別のとこクリックしてpickerを閉じないと、値が確定されないようになってる
> そんで、たぶんtimepickerを開いたままチェックボタン押してるから、編集前の13:00のままになってしまってるんだわ

なんか改めて確認してみたらどうもそういうことじゃないっぽいな、timepicker開いたままチェック押してもちゃんと指定した時間が登録されるけど、なんでかcompleteタブに移動しよる
バグやこれ
